-- Insert sample AI tools with comprehensive data
INSERT INTO tools (
    name, developer, category, primary_function, description, features, pricing,
    pricing_details, platform_compatibility, rating, reviews, logo, official_website,
    release_date, last_update, supported_languages, os_requirements, deployment_type,
    integration_capabilities, expertise_level, training_resources, compliance_certifications,
    advantages, limitations, hardware_requirements, security_features, technical_specs,
    model_customization, api_documentation, technology_stack, data_formats,
    performance_metrics, version_info, energy_metrics, community_size, vendor_info,
    access_control, bias_mitigation, operational_costs, legal_info, license_type,
    case_studies, localization, tags, slug
) VALUES
(
    'NeuralVision Pro', 'AI Dynamics Inc.', 'Computer Vision',
    'Advanced Image Recognition and Analysis',
    'Enterprise-grade computer vision platform for real-time image analysis and object detection',
    ARRAY['Real-time object detection', 'Facial recognition', 'Scene analysis', 'Custom model training', 'Batch processing'],
    'Paid',
    '{"free_tier": {"features": ["Basic object detection", "100 API calls/day"], "limitations": ["Limited model customization"]}, "paid_tiers": [{"name": "Professional", "price": 99.99, "billing": "monthly", "features": ["Unlimited API calls", "Custom model training"]}]}'::jsonb,
    ARRAY['Web', 'API', 'Docker'],
    4.8, 1250,
    'https://images.unsplash.com/photo-1561736778-92e52a7769ef',
    'https://example.com/neuralvision',
    '2023-06-15', '2024-02-20',
    ARRAY['English', 'Spanish', 'Mandarin'],
    ARRAY['Linux', 'Windows Server 2019+'],
    ARRAY['Cloud', 'On-premise'],
    ARRAY['REST API', 'Python SDK', 'JavaScript SDK', 'Docker containers'],
    'Advanced',
    ARRAY['Documentation', 'Video tutorials', 'Community forums', 'Expert support'],
    ARRAY['SOC 2', 'GDPR', 'HIPAA'],
    ARRAY['High accuracy', 'Low latency', 'Scalable infrastructure'],
    ARRAY['Requires high-end GPU', 'Limited offline capabilities'],
    ARRAY['NVIDIA GPU', '16GB RAM', '100GB storage'],
    ARRAY['End-to-end encryption', 'Role-based access', 'Audit logging'],
    '{"algorithms": ["YOLO", "ResNet", "SSD"], "frameworks": ["TensorFlow", "PyTorch"], "models": ["Custom CNN"]}'::jsonb,
    ARRAY['Transfer learning', 'Fine-tuning', 'Custom architecture'],
    'https://api.example.com/docs',
    ARRAY['Python', 'TensorFlow', 'Docker', 'Kubernetes'],
    ARRAY['JPEG', 'PNG', 'TIFF', 'BMP'],
    '{"accuracy": 98.5, "latency": 150, "throughput": 1000}'::jsonb,
    '{"current": "2.3.0", "changelog": ["Improved accuracy", "Reduced latency"]}'::jsonb,
    '{"consumption": 450, "carbon_footprint": 0.8}'::jsonb,
    25000,
    '{"company": "AI Dynamics Inc.", "founded": "2020", "size": "100-500", "customers": ["Tesla", "Boeing", "Samsung"]}'::jsonb,
    ARRAY['SSO', 'API keys', '2FA'],
    ARRAY['Regular bias audits', 'Diverse training data', 'Transparency reports'],
    '{"setup": 5000, "monthly": 999, "usage_based": true}'::jsonb,
    'Enterprise license with custom terms',
    'Enterprise',
    ARRAY['Manufacturing quality control', 'Security surveillance', 'Medical imaging'],
    ARRAY['en-US', 'es-ES', 'zh-CN'],
    ARRAY['Computer Vision', 'AI', 'Enterprise'],
    'neuralvision-pro'
),
(
    'LangChain Studio', 'CodeCraft Labs', 'NLP',
    'Natural Language Processing and Generation',
    'Comprehensive NLP platform for text analysis, generation, and language understanding',
    ARRAY['Text classification', 'Named entity recognition', 'Sentiment analysis', 'Language generation'],
    'Freemium',
    '{"free_tier": {"features": ["Basic NLP", "5000 tokens/day"], "limitations": ["API rate limits"]}, "paid_tiers": [{"name": "Business", "price": 199.99, "billing": "monthly", "features": ["Unlimited tokens", "Priority support"]}]}'::jsonb,
    ARRAY['Web', 'API', 'Python'],
    4.9, 2800,
    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5',
    'https://example.com/langchain',
    '2023-08-01', '2024-03-01',
    ARRAY['English', 'French', 'German', 'Japanese'],
    ARRAY['Any modern OS'],
    ARRAY['Cloud', 'Hybrid'],
    ARRAY['REST API', 'GraphQL', 'Python SDK'],
    'Intermediate',
    ARRAY['Interactive tutorials', 'API documentation', 'Use case examples'],
    ARRAY['ISO 27001', 'GDPR'],
    ARRAY['Multi-language support', 'High accuracy', 'Easy integration'],
    ARRAY['Limited offline support', 'Resource intensive'],
    ARRAY['8GB RAM', '50GB storage'],
    ARRAY['Data encryption', 'Access controls'],
    '{"algorithms": ["Transformer", "BERT", "GPT"], "frameworks": ["PyTorch", "Hugging Face"]}'::jsonb,
    ARRAY['Fine-tuning', 'Prompt engineering'],
    'https://docs.example.com/langchain',
    ARRAY['Python', 'PyTorch', 'FastAPI'],
    ARRAY['TXT', 'JSON', 'CSV'],
    '{"accuracy": 95.0, "latency": 200}'::jsonb,
    '{"current": "1.5.0", "changelog": ["New language models", "Improved accuracy"]}'::jsonb,
    '{"consumption": 300, "carbon_footprint": 0.5}'::jsonb,
    18000,
    '{"company": "CodeCraft Labs", "founded": "2021", "size": "50-100", "customers": ["Microsoft", "Adobe"]}'::jsonb,
    ARRAY['OAuth', 'API keys'],
    ARRAY['Bias detection', 'Fairness metrics'],
    '{"setup": 0, "monthly": 199, "usage_based": true}'::jsonb,
    'Apache 2.0 with commercial terms',
    'Commercial',
    ARRAY['Content generation', 'Customer support', 'Market analysis'],
    ARRAY['en', 'fr', 'de', 'ja'],
    ARRAY['NLP', 'AI', 'Language'],
    'langchain-studio'
),
(
    'AutoML Master', 'DataSense Technologies', 'Machine Learning',
    'Automated Machine Learning Platform',
    'No-code platform for automated model training, deployment, and monitoring',
    ARRAY['Automated feature engineering', 'Model selection', 'Hyperparameter tuning', 'Model deployment'],
    'Freemium',
    '{"free_tier": {"features": ["Basic automation", "2 projects"], "limitations": ["Limited compute"]}, "paid_tiers": [{"name": "Enterprise", "price": 499.99, "billing": "monthly", "features": ["Unlimited projects", "Advanced features"]}]}'::jsonb,
    ARRAY['Web', 'API'],
    4.7, 3500,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71',
    'https://example.com/automl',
    '2023-09-15', '2024-03-10',
    ARRAY['English'],
    ARRAY['Web browser'],
    ARRAY['Cloud'],
    ARRAY['REST API', 'Python SDK', 'R SDK'],
    'Beginner',
    ARRAY['Getting started guide', 'Video tutorials', 'Community support'],
    ARRAY['SOC 2', 'GDPR'],
    ARRAY['No coding required', 'Fast deployment', 'Model monitoring'],
    ARRAY['Limited model customization', 'Fixed architectures'],
    ARRAY['4GB RAM', 'Modern browser'],
    ARRAY['Data encryption', 'User authentication'],
    '{"algorithms": ["Random Forest", "XGBoost", "Neural Networks"], "frameworks": ["scikit-learn", "TensorFlow"]}'::jsonb,
    ARRAY['Automated optimization', 'Model selection'],
    'https://docs.example.com/automl',
    ARRAY['Python', 'R', 'JavaScript'],
    ARRAY['CSV', 'JSON', 'Excel'],
    '{"accuracy": 92.0, "latency": 300}'::jsonb,
    '{"current": "3.0.0", "changelog": ["New algorithms", "Improved UI"]}'::jsonb,
    '{"consumption": 200, "carbon_footprint": 0.3}'::jsonb,
    15000,
    '{"company": "DataSense Technologies", "founded": "2022", "size": "20-50", "customers": ["IBM", "Oracle"]}'::jsonb,
    ARRAY['Email/Password', '2FA'],
    ARRAY['Automated bias detection', 'Fair model selection'],
    '{"setup": 0, "monthly": 499, "usage_based": false}'::jsonb,
    'Proprietary',
    'Commercial',
    ARRAY['Financial forecasting', 'Customer churn prediction'],
    ARRAY['en-US'],
    ARRAY['AutoML', 'AI', 'No-Code'],
    'automl-master'
),
(
    'RoboFlow AI', 'Automation Dynamics', 'Robotics',
    'Robotic Process Automation',
    'Enterprise automation platform for robotic process automation and workflow optimization',
    ARRAY['Process automation', 'Workflow optimization', 'Bot management', 'Analytics'],
    'Paid',
    '{"free_tier": null, "paid_tiers": [{"name": "Enterprise", "price": 999.99, "billing": "monthly", "features": ["Full automation suite", "Custom integrations"]}]}'::jsonb,
    ARRAY['Windows', 'Linux', 'Mac'],
    4.6, 1800,
    'https://images.unsplash.com/photo-1485827404703-89b55fcc595e',
    'https://example.com/roboflow',
    '2023-07-01', '2024-02-28',
    ARRAY['English', 'Japanese'],
    ARRAY['Windows 10+', 'Ubuntu 20.04+', 'macOS 12+'],
    ARRAY['On-premise', 'Hybrid'],
    ARRAY['.NET SDK', 'Java SDK', 'Python SDK'],
    'Advanced',
    ARRAY['Certification program', 'Enterprise training', 'Documentation'],
    ARRAY['ISO 27001', 'SOC 2', 'HIPAA'],
    ARRAY['Enterprise-grade', 'Scalable', 'Secure'],
    ARRAY['Complex setup', 'Requires training'],
    ARRAY['8GB RAM', '4 CPU cores', 'SSD storage'],
    ARRAY['Enterprise security', 'Audit trails', 'Encryption'],
    '{"algorithms": ["Process Mining", "ML Optimization"], "frameworks": [".NET", "Java"]}'::jsonb,
    ARRAY['Custom workflows', 'Process templates'],
    'https://docs.example.com/roboflow',
    ARRAY['.NET', 'Java', 'Python'],
    ARRAY['XML', 'JSON', 'CSV'],
    '{"accuracy": 99.0, "throughput": 5000}'::jsonb,
    '{"current": "4.2.0", "changelog": ["New features", "Security updates"]}'::jsonb,
    '{"consumption": 500, "carbon_footprint": 1.0}'::jsonb,
    12000,
    '{"company": "Automation Dynamics", "founded": "2019", "size": "200-500", "customers": ["Toyota", "GE"]}'::jsonb,
    ARRAY['AD/LDAP', 'SSO', 'RBAC'],
    ARRAY['Process fairness', 'Audit logging'],
    '{"setup": 10000, "monthly": 999, "usage_based": false}'::jsonb,
    'Enterprise license',
    'Enterprise',
    ARRAY['Manufacturing', 'Healthcare', 'Finance'],
    ARRAY['en-US', 'ja-JP'],
    ARRAY['RPA', 'Automation', 'Enterprise'],
    'roboflow-ai'
),
(
    'DataSense Analytics', 'Insight Systems', 'Data Analysis',
    'Advanced Data Analytics and Visualization',
    'AI-powered analytics platform for business intelligence and data visualization',
    ARRAY['Predictive analytics', 'Interactive dashboards', 'Automated reporting', 'Data integration'],
    'Paid',
    '{"free_tier": null, "paid_tiers": [{"name": "Business", "price": 299.99, "billing": "monthly", "features": ["Full analytics suite", "Custom dashboards"]}]}'::jsonb,
    ARRAY['Web', 'Desktop'],
    4.8, 2200,
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71',
    'https://example.com/datasense',
    '2023-10-01', '2024-03-15',
    ARRAY['English', 'Spanish', 'French'],
    ARRAY['Modern web browser', 'Windows 10+'],
    ARRAY['Cloud', 'Hybrid'],
    ARRAY['REST API', 'Python SDK', 'R SDK'],
    'Intermediate',
    ARRAY['Online courses', 'Certification', 'Support portal'],
    ARRAY['SOC 2', 'GDPR', 'ISO 27001'],
    ARRAY['Real-time analytics', 'Custom visualizations', 'AI insights'],
    ARRAY['Learning curve', 'Data preparation needed'],
    ARRAY['8GB RAM', 'Modern GPU'],
    ARRAY['End-to-end encryption', 'Access controls'],
    '{"algorithms": ["Statistical Analysis", "Machine Learning"], "frameworks": ["TensorFlow", "R"]}'::jsonb,
    ARRAY['Custom models', 'Visual builders'],
    'https://docs.example.com/datasense',
    ARRAY['Python', 'R', 'JavaScript'],
    ARRAY['CSV', 'JSON', 'SQL', 'Excel'],
    '{"accuracy": 96.0, "latency": 250}'::jsonb,
    '{"current": "2.1.0", "changelog": ["New visualizations", "Performance improvements"]}'::jsonb,
    '{"consumption": 350, "carbon_footprint": 0.6}'::jsonb,
    20000,
    '{"company": "Insight Systems", "founded": "2021", "size": "100-200", "customers": ["Deloitte", "KPMG"]}'::jsonb,
    ARRAY['SSO', '2FA', 'RBAC'],
    ARRAY['Fair analysis', 'Bias detection'],
    '{"setup": 2000, "monthly": 299, "usage_based": true}'::jsonb,
    'Commercial license',
    'Commercial',
    ARRAY['Financial analysis', 'Marketing analytics', 'Operations'],
    ARRAY['en', 'es', 'fr'],
    ARRAY['Analytics', 'BI', 'Data Science'],
    'datasense-analytics'
);